FROM arm32v6/alpine:3.21@sha256:3ec4e00c3672159e05732bcef6c97beb6ceaad9e87a76df277563cadeb95b37d
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/errors"]
ENTRYPOINT ["/usr/bin/errors"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/errors health

COPY bin/errors /usr/bin/errors
