FROM i386/alpine:3.20@sha256:bdea2fc06762f63b168e481c88a732e73d856b98c9a504f2c749c867ef9d41ac
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/errors"]
ENTRYPOINT ["/usr/bin/errors"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/errors health

COPY bin/errors /usr/bin/errors
