FROM i386/alpine:3.21@sha256:fb70fd49b7da8155e6502719154eb96ef6fede4947a33dcd5497c4e7124fd707
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/errors"]
ENTRYPOINT ["/usr/bin/errors"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/errors health

COPY bin/errors /usr/bin/errors
