FROM arm32v6/alpine:3.16@sha256:5da989a9a3a08357bc7c00bd46c3ed782e1aeefc833e0049e6834ec1dcad8a42
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/errors"]
ENTRYPOINT ["/usr/bin/errors"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/errors health

COPY bin/errors /usr/bin/errors
