FROM arm64v8/alpine:3.18@sha256:b312e4b0e2c665d634602411fcb7c2699ba748c36f59324457bc17de485f36f6
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/errors"]
ENTRYPOINT ["/usr/bin/errors"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/errors health

COPY bin/errors /usr/bin/errors
