---
server:
  addr: 0.0.0.0:8080
  host: http://localhost:8080
  pprof: false
  root: /
  cert: ~
  key: ~
  strict_curves: false
  strict_ciphers: false
  templates: /usr/share/errors/templates
  errors: /etc/errors/errors.yaml

metrics:
  addr: 0.0.0.0:8081
  token: ~

log:
  level: info
  pretty: true
  color: true

...
